import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import Link from "next/link";
import Image from "next/image";
import "./globals.css";
import logo from "@/public/logo.svg";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={inter.className}
      >
        <header className="h-[200px] bg-[#0d0d0d] text-white p-4 flex justify-center items-center">
          {/* Logo */}
          <Link href="/" className="flex items-center">
            <Image src={logo} alt="Logo" height={48} className="mr-2" />
          </Link>
        </header>

        {/* Main content */}
        <main className="container mx-auto px-4">{children}</main>
      </body>
    </html>
  );
}
